### PR TITLE
Feature/static markers

### PR DESCRIPTION
**Pull request by abrathovde**

### CODE REVIEW

**Comment by abrathovde** [comment]
Took me a little bit to wrap my head around the concepts. Think of this as initial setup for marker support. Hoping to add more functionality in the future.

**Comment by abrathovde** [comment]
@xclud ?

**Comment by xclud** [comment]
@abrathovde I appreciate your job on the project. But it does not show any markers yet and you only added an array to hold future markers.

BTW, for future PRs, please do not move the code up and down in lines. Most of the changes i see in your PR is moving variables up and down.

I am looking forward to your PRs. I see you have forked the project and you have gone further than this PR. Thanks.

**Comment by abrathovde** [comment]
It does show markers...

```
...
        new MapView(
            initialLocation: const LatLong(48.8566, 2.3522),
            inititialZoom: 9.0,
            markers: [
              Marker(position: LatLong(48.8566, 2.3522)),
            ],
...
```

**Pull request closed without merging**
