### PR TITLE
adding support for more map gestures

### PR DESCRIPTION
**Pull request by abrathovde**

### CODE REVIEW

**Comment by xclud** [comment]
@abrathovde thank you for your contribution. Passing the event handlers using a class object (MapGestures class in your PR) is not a common practice in Flutter.

Is there any reason your are passing a MapGestures object ? If No, I'd appreciate if you eliminate the class and i will merge the PR.

**Comment by abrathovde** [comment]
I was trying to keep the number of parameters passed into the constructor relatively low. It's something that's extensible if more actions needed to be added and the number of parameters to the constructor will be remain the same.

**Comment by xclud** [comment]
We have optional parameters for this :)

**Comment by abrathovde** [comment]
Fair enough. I'll remove it.

**Comment by xclud** [comment]
Thanks you. Merged.

**Pull request merged**
